/* 编辑此文件中的品牌文案与商品数据。所有金额使用整数分。 */
window.SHOP = {
  brand: '待梦归数模',
  storageKey: 'daimenggui-demo-v1',
  coupon: { code: 'DEMO20', percent: 20 },
  products: [
    {id:'optimization',type:'case',event:'国赛',title:'多目标优化建模实战',subtitle:'从问题拆解到 Pareto 最优解',desc:'以资源配置问题为例，串联目标函数、约束条件、求解与结果分析，理解一个模型如何落地。',price:12900,version:'2.1',tag:'入门推荐',level:'进阶',files:['案例论文结构说明','Python 求解代码示例','结果图表说明'],format:'论文 + Python + 图表',color:'blue',graph:'pareto',topics:['多目标规划','NSGA-II','灵敏度分析'],outline:['问题重述与建模假设','目标函数与约束构建','NSGA-II 求解流程','Pareto 前沿与方案评价','敏感性分析与论文表达']},
    {id:'python-course',type:'course',event:'通用',title:'Python 数学建模系统课',subtitle:'用代码，把建模方法真正跑通',desc:'从数据清洗和可视化起步，逐步学习评价、预测与优化模型。每一节围绕一个具体问题练习。',price:19900,version:'1.3',tag:'体系学习',level:'零基础',files:['课程文字试看','练习任务说明'],format:'12 个章节 · 代码练习',color:'purple',graph:'scatter',topics:['Python','数据分析','可视化'],outline:['01 Python 环境与数据结构','02 NumPy 数组计算','03 Pandas 数据清洗','04 Matplotlib 图表表达','05 综合评价模型','06 线性规划','07 回归与预测','08 时间序列基础','09 聚类分析','10 启发式算法','11 结果检验','12 项目复盘']},
    {id:'evaluation',type:'idea',event:'国赛',title:'综合评价模型思路手册',subtitle:'AHP · 熵权法 · TOPSIS',desc:'什么时候用层次分析，什么时候用客观赋权？用清晰的步骤和对照案例，建立完整的评价问题解题思路。',price:3900,version:'2.0',tag:'可免费试读',level:'入门',files:['评价模型示例笔记'],format:'思路文档 · 免费试读 20%',color:'teal',graph:'radar',topics:['AHP','熵权法','TOPSIS'],outline:['识别评价对象与指标','正向化与无量纲处理','主客观权重选择','TOPSIS 距离与排序','结果稳健性检验']},
    {id:'forecast',type:'case',event:'美赛',title:'时间序列预测完整案例',subtitle:'把变化的趋势，转化为可验证的预测',desc:'以示例需求序列为研究对象，完成趋势观察、基线预测、训练验证分离和误差分析。',price:9900,version:'1.2',tag:'案例研读',level:'进阶',files:['预测案例说明','Python 示例片段','误差指标笔记'],format:'论文 + Python + 示例数据',color:'indigo',graph:'line',topics:['ARIMA','时间序列','误差分析'],outline:['数据探索与缺失值处理','平稳性与差分','基线和候选模型','滚动验证与误差分析','预测区间与局限性']},
    {id:'graph-idea',type:'idea',event:'华为杯',title:'图论与路径规划解题指南',subtitle:'从一张网络，找到问题的结构',desc:'掌握网络抽象、最短路径与组合优化的常见切入点，读懂模型选择背后的逻辑。',price:4900,version:'1.0',tag:'可免费试读',level:'进阶',files:['路径规划示例笔记'],format:'思路文档 · 免费试读 20%',color:'slate',graph:'network',topics:['图论','Dijkstra','路径规划'],outline:['节点与边的定义','最短路径和最小生成树','多约束路径规划','复杂度与算法选择','模型验证与表达']},
    {id:'writing-course',type:'course',event:'通用',title:'建模论文写作与图表表达',subtitle:'让你的模型，也能被清楚地读懂',desc:'围绕摘要、假设、结果解释与图表规范，练习从计算过程到清晰论文的表达转换。',price:7900,version:'1.1',tag:'写作专项',level:'入门',files:['论文表达文字试看','写作练习说明'],format:'6 个章节 · 写作练习',color:'sky',graph:'bars',topics:['论文结构','LaTeX','学术图表'],outline:['01 论文的论证主线','02 如何写好摘要','03 假设与符号说明','04 结果与图表表达','05 优缺点与模型推广','06 全文检查与排版']},
    {id:'ecology',type:'case',event:'华为杯',title:'生态系统动力学建模案例',subtitle:'理解系统如何随时间演化',desc:'以简化的种群系统为例，学习微分方程建模、数值求解、参数分析和模型局限。',price:11900,version:'1.0',tag:'专题研读',level:'进阶',files:['动力学案例说明','ODE 求解代码示例'],format:'论文 + Python + 图表',color:'teal',graph:'line',topics:['微分方程','数值模拟','参数分析'],outline:['状态变量与系统边界','微分方程建立','数值积分与可视化','参数敏感性分析','模型假设的局限']},
    {id:'data-idea',type:'idea',event:'美赛',title:'数据预处理与可视化速查',subtitle:'从原始数据，到可信的模型输入',desc:'整理缺失值、异常值、特征变换和图表选择的常见处理流程，建立可复现的数据分析习惯。',price:2900,version:'1.4',tag:'可免费试读',level:'零基础',files:['数据处理示例笔记'],format:'思路文档 · 免费试读 20%',color:'purple',graph:'scatter',topics:['数据清洗','特征处理','可视化'],outline:['先检查数据类型','缺失与异常值策略','特征变换与标准化','图表选择和阅读','复现清单与检查']},
    {id:'membership',type:'member',event:'通用',title:'研习会员月度计划',subtitle:'持续学习的一个起点',desc:'会员权益方案演示。包含思路库阅读、学习资料更新提醒及每月一次课程咨询入口。',price:9900,version:'1.0',tag:'会员方案',level:'通用',files:['会员权益演示说明'],format:'30 天 · 不自动续费',color:'blue',graph:'network',topics:['思路库','学习计划','课程咨询'],outline:['思路库内容阅读','资料更新提醒','每月一次课程咨询','30 天有效期，不自动续费']}
  ]
};
